---
site:
  url: http://10.2.5.139:5000
  title: 临沂重要商品追溯种植系统
  tips: 用户名或者密码错误
  #suffix: "@126.com"
  user: user01
  passwd: 123456

loc:
  username_loc: (By.XPATH, '//*[@id="ext-element-1"]/div/div/div[2]/div/div/form/div[1]/div/div/div/input')
  password_loc: (By.XPATH, '//*[@id="ext-element-1"]/div/div/div[2]/div/div/form/div[2]/div/div/div/input')
  submit_loc: (By.XPATH, '//*[@id="ext-element-1"]/div/div/div[2]/div/div/form/div[3]/div/div/button/span')
  span_loc: (By.ID, 'nerror')
  dynpw_loc: (By.ID, 'lbDynPw')
  userid_loc: (By.ID, 'spnUid')
  logout_loc: (By.ID, '_mail_component_41_41')